In [16]:
import numpy as np
import torch

In [8]:
scalar = torch.tensor(torch.pi)
scalar

tensor(3.1416)

In [9]:
scalar.shape

torch.Size([])

In [29]:
array = torch.tensor((range(10)))
array

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
array.shape

torch.Size([10])

In [14]:
matrix = torch.tensor((range(4), range(4, 8), range(8, 12), range(12, 16)))
matrix

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [15]:
matrix.shape

torch.Size([4, 4])

In [23]:
tensor = torch.tensor(np.random.rand(2, 2, 2))
tensor

tensor([[[0.2885, 0.1838],
         [0.4376, 0.4599]],

        [[0.5787, 0.7365],
         [0.1591, 0.0459]]], dtype=torch.float64)

In [24]:
tensor.shape

torch.Size([2, 2, 2])

In [27]:
np.pi

3.141592653589793