In [1]:
!python --version

Python 3.14.3


The system cannot find the path specified.


In [4]:
import numpy as np
import skimage
import scipy
import cv2
from PIL import Image

import rootskel

In [8]:
roots = Image.open(r"./20260312_103230.jpg")
roots.mode # RGB is good

'RGB'

In [13]:
roots = np.array(roots)

In [18]:
greyscale = cv2.cvtColor(src=roots, code=cv2.COLOR_RGB2GRAY)

In [19]:
greyscale

array([[ 84,  85,  86, ..., 116, 115, 115],
       [ 83,  84,  86, ..., 117, 117, 117],
       [ 83,  84,  86, ..., 119, 118, 118],
       ...,
       [102, 100,  99, ..., 168, 166, 166],
       [101, 100,  98, ..., 168, 168, 167],
       [101,  99,  98, ..., 168, 168, 167]],
      shape=(3966, 3356), dtype=uint8)

In [20]:
cv2.bitwise_not(src=greyscale, dst=greyscale)

array([[171, 170, 169, ..., 139, 140, 140],
       [172, 171, 169, ..., 138, 138, 138],
       [172, 171, 169, ..., 136, 137, 137],
       ...,
       [153, 155, 156, ...,  87,  89,  89],
       [154, 155, 157, ...,  87,  87,  88],
       [154, 156, 157, ...,  87,  87,  88]],
      shape=(3966, 3356), dtype=uint8)

In [21]:
greyscale

array([[171, 170, 169, ..., 139, 140, 140],
       [172, 171, 169, ..., 138, 138, 138],
       [172, 171, 169, ..., 136, 137, 137],
       ...,
       [153, 155, 156, ...,  87,  89,  89],
       [154, 155, 157, ...,  87,  87,  88],
       [154, 156, 157, ...,  87,  87,  88]],
      shape=(3966, 3356), dtype=uint8)